//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_AppointmentDiary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FP_AppointmentDiary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap accepted_48 {
            get {
                object obj = ResourceManager.GetObject("accepted_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_16 {
            get {
                object obj = ResourceManager.GetObject("add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_48 {
            get {
                object obj = ResourceManager.GetObject("add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap app_48 {
            get {
                object obj = ResourceManager.GetObject("app_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_48 {
            get {
                object obj = ResourceManager.GetObject("arrow_down_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_green_48 {
            get {
                object obj = ResourceManager.GetObject("arrow_down_green_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_left_48 {
            get {
                object obj = ResourceManager.GetObject("arrow_left_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_left_green_48 {
            get {
                object obj = ResourceManager.GetObject("arrow_left_green_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right_48 {
            get {
                object obj = ResourceManager.GetObject("arrow_right_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right_green_48 {
            get {
                object obj = ResourceManager.GetObject("arrow_right_green_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_up_48 {
            get {
                object obj = ResourceManager.GetObject("arrow_up_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_up_green_48 {
            get {
                object obj = ResourceManager.GetObject("arrow_up_green_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap beer_48 {
            get {
                object obj = ResourceManager.GetObject("beer_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blinklist_48 {
            get {
                object obj = ResourceManager.GetObject("blinklist_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blue_speech_bubble_48 {
            get {
                object obj = ResourceManager.GetObject("blue_speech_bubble_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap book_48 {
            get {
                object obj = ResourceManager.GetObject("book_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap box_48 {
            get {
                object obj = ResourceManager.GetObject("box_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap box_download_48 {
            get {
                object obj = ResourceManager.GetObject("box_download_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap box_upload_48 {
            get {
                object obj = ResourceManager.GetObject("box_upload_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera_48 {
            get {
                object obj = ResourceManager.GetObject("camera_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera_add_48 {
            get {
                object obj = ResourceManager.GetObject("camera_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera_delete_48 {
            get {
                object obj = ResourceManager.GetObject("camera_delete_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera_noflash_48 {
            get {
                object obj = ResourceManager.GetObject("camera_noflash_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera_noflash_add_48 {
            get {
                object obj = ResourceManager.GetObject("camera_noflash_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera_noflash_delete_48 {
            get {
                object obj = ResourceManager.GetObject("camera_noflash_delete_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera_noflash_warning_48 {
            get {
                object obj = ResourceManager.GetObject("camera_noflash_warning_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera_warning_48 {
            get {
                object obj = ResourceManager.GetObject("camera_warning_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel_16 {
            get {
                object obj = ResourceManager.GetObject("cancel_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel_48 {
            get {
                object obj = ResourceManager.GetObject("cancel_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cd_48 {
            get {
                object obj = ResourceManager.GetObject("cd_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap circle_blue {
            get {
                object obj = ResourceManager.GetObject("circle_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap circle_green {
            get {
                object obj = ResourceManager.GetObject("circle_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap circle_orange {
            get {
                object obj = ResourceManager.GetObject("circle_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap circle_red {
            get {
                object obj = ResourceManager.GetObject("circle_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clock_48 {
            get {
                object obj = ResourceManager.GetObject("clock_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap coffee_48 {
            get {
                object obj = ResourceManager.GetObject("coffee_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap coffee_mug {
            get {
                object obj = ResourceManager.GetObject("coffee_mug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap comment_48 {
            get {
                object obj = ResourceManager.GetObject("comment_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap comment_add_48 {
            get {
                object obj = ResourceManager.GetObject("comment_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap comment_remove_48 {
            get {
                object obj = ResourceManager.GetObject("comment_remove_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap comment_warning_48 {
            get {
                object obj = ResourceManager.GetObject("comment_warning_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computer_48 {
            get {
                object obj = ResourceManager.GetObject("computer_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap creditcard_american_express {
            get {
                object obj = ResourceManager.GetObject("creditcard_american_express", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap creditcard_cirrus {
            get {
                object obj = ResourceManager.GetObject("creditcard_cirrus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap creditcard_mastercard {
            get {
                object obj = ResourceManager.GetObject("creditcard_mastercard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap creditcard_paypal {
            get {
                object obj = ResourceManager.GetObject("creditcard_paypal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap creditcard_solo {
            get {
                object obj = ResourceManager.GetObject("creditcard_solo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap creditcard_switch {
            get {
                object obj = ResourceManager.GetObject("creditcard_switch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap creditcard_visa {
            get {
                object obj = ResourceManager.GetObject("creditcard_visa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cross_48 {
            get {
                object obj = ResourceManager.GetObject("cross_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database_48 {
            get {
                object obj = ResourceManager.GetObject("database_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database_add_48 {
            get {
                object obj = ResourceManager.GetObject("database_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database_remove_48 {
            get {
                object obj = ResourceManager.GetObject("database_remove_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database_warning_48 {
            get {
                object obj = ResourceManager.GetObject("database_warning_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delicious_48 {
            get {
                object obj = ResourceManager.GetObject("delicious_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap designfloat_48 {
            get {
                object obj = ResourceManager.GetObject("designfloat_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap digg_48 {
            get {
                object obj = ResourceManager.GetObject("digg_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap feedburner_48 {
            get {
                object obj = ResourceManager.GetObject("feedburner_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flickr_48 {
            get {
                object obj = ResourceManager.GetObject("flickr_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floppy_disk_48 {
            get {
                object obj = ResourceManager.GetObject("floppy_disk_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_48 {
            get {
                object obj = ResourceManager.GetObject("folder_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_add_48 {
            get {
                object obj = ResourceManager.GetObject("folder_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_delete_48 {
            get {
                object obj = ResourceManager.GetObject("folder_delete_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_warning_48 {
            get {
                object obj = ResourceManager.GetObject("folder_warning_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap furl_48 {
            get {
                object obj = ResourceManager.GetObject("furl_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap globe_48 {
            get {
                object obj = ResourceManager.GetObject("globe_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap google_48 {
            get {
                object obj = ResourceManager.GetObject("google_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap heart_48 {
            get {
                object obj = ResourceManager.GetObject("heart_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap home_48 {
            get {
                object obj = ResourceManager.GetObject("home_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image_48 {
            get {
                object obj = ResourceManager.GetObject("image_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image_add_48 {
            get {
                object obj = ResourceManager.GetObject("image_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image_delete_48 {
            get {
                object obj = ResourceManager.GetObject("image_delete_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image_warning_48 {
            get {
                object obj = ResourceManager.GetObject("image_warning_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightbulb_48 {
            get {
                object obj = ResourceManager.GetObject("lightbulb_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_48 {
            get {
                object obj = ResourceManager.GetObject("lock_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_open_48 {
            get {
                object obj = ResourceManager.GetObject("lock_open_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_48 {
            get {
                object obj = ResourceManager.GetObject("mail_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_add_48 {
            get {
                object obj = ResourceManager.GetObject("mail_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_delete_48 {
            get {
                object obj = ResourceManager.GetObject("mail_delete_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_forward_48 {
            get {
                object obj = ResourceManager.GetObject("mail_forward_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_reply_48 {
            get {
                object obj = ResourceManager.GetObject("mail_reply_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_spam_48 {
            get {
                object obj = ResourceManager.GetObject("mail_spam_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_write_48 {
            get {
                object obj = ResourceManager.GetObject("mail_write_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mixx_48 {
            get {
                object obj = ResourceManager.GetObject("mixx_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mouse_48 {
            get {
                object obj = ResourceManager.GetObject("mouse_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_48 {
            get {
                object obj = ResourceManager.GetObject("navigate_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newspaper_48 {
            get {
                object obj = ResourceManager.GetObject("newspaper_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paper_48 {
            get {
                object obj = ResourceManager.GetObject("paper_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paper_content_48 {
            get {
                object obj = ResourceManager.GetObject("paper_content_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paper_content_chart_48 {
            get {
                object obj = ResourceManager.GetObject("paper_content_chart_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paper_content_pencil_48 {
            get {
                object obj = ResourceManager.GetObject("paper_content_pencil_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paper_pencil_48 {
            get {
                object obj = ResourceManager.GetObject("paper&pencil_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pencil_48 {
            get {
                object obj = ResourceManager.GetObject("pencil_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pie_chart_48 {
            get {
                object obj = ResourceManager.GetObject("pie_chart_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap printer_48 {
            get {
                object obj = ResourceManager.GetObject("printer_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap questionmark_48 {
            get {
                object obj = ResourceManager.GetObject("questionmark_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reddit_48 {
            get {
                object obj = ResourceManager.GetObject("reddit_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_48 {
            get {
                object obj = ResourceManager.GetObject("refresh_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rss_48 {
            get {
                object obj = ResourceManager.GetObject("rss_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_48 {
            get {
                object obj = ResourceManager.GetObject("search_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap smile_grin_48 {
            get {
                object obj = ResourceManager.GetObject("smile_grin_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap smile_sad_48 {
            get {
                object obj = ResourceManager.GetObject("smile_sad_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap spanner_48 {
            get {
                object obj = ResourceManager.GetObject("spanner_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap speech_bubble_48 {
            get {
                object obj = ResourceManager.GetObject("speech_bubble_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap star_48 {
            get {
                object obj = ResourceManager.GetObject("star_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap star_half_48 {
            get {
                object obj = ResourceManager.GetObject("star_half_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap star_off_48 {
            get {
                object obj = ResourceManager.GetObject("star_off_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sumbleupon_48 {
            get {
                object obj = ResourceManager.GetObject("sumbleupon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_48 {
            get {
                object obj = ResourceManager.GetObject("table_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_green_48 {
            get {
                object obj = ResourceManager.GetObject("table_green_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tabs_48 {
            get {
                object obj = ResourceManager.GetObject("tabs_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap technorati_48 {
            get {
                object obj = ResourceManager.GetObject("technorati_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbs_down_48 {
            get {
                object obj = ResourceManager.GetObject("thumbs_down_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbs_up_48 {
            get {
                object obj = ResourceManager.GetObject("thumbs_up_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap twitter_48 {
            get {
                object obj = ResourceManager.GetObject("twitter_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap twitter_boxed_48 {
            get {
                object obj = ResourceManager.GetObject("twitter_boxed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap usb_48 {
            get {
                object obj = ResourceManager.GetObject("usb_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_48 {
            get {
                object obj = ResourceManager.GetObject("user_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_add_48 {
            get {
                object obj = ResourceManager.GetObject("user_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_delete_48 {
            get {
                object obj = ResourceManager.GetObject("user_delete_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_two_delete_48 {
            get {
                object obj = ResourceManager.GetObject("user_two_delete_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_warning_48 {
            get {
                object obj = ResourceManager.GetObject("user_warning_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users_two_48 {
            get {
                object obj = ResourceManager.GetObject("users_two_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users_two_add_48 {
            get {
                object obj = ResourceManager.GetObject("users_two_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users_two_warning_48 {
            get {
                object obj = ResourceManager.GetObject("users_two_warning_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning_16 {
            get {
                object obj = ResourceManager.GetObject("warning_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning_48 {
            get {
                object obj = ResourceManager.GetObject("warning_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yahoo_48 {
            get {
                object obj = ResourceManager.GetObject("yahoo_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
